<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>reshapr-e2e-tests</artifactId>
  <parent>
    <groupId>io.reshapr</groupId>
    <artifactId>reshapr-parent</artifactId>
    <version>0.2.4-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <name>Reshapr E2E Tests</name>
  <description>End-to-End tests spanning Control Plane and Proxy</description>

  <dependencies>
    <dependency>
      <groupId>io.reshapr</groupId>
      <artifactId>reshapr-ctrl</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.reshapr</groupId>
      <artifactId>reshapr</artifactId> <!-- proxy module -->
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>
</project>
